# **NumPy Installation**

Google Colab and Anaconda Package include Python, NumPy, and other commonly used packages for scientific computing and data science.

NumPy can be installed with conda, with pip, or with a package manager on different OS.

If you use conda, you can install it with:
**conda install numpy**

If you use pip, you can install it with:
**pip install numpy**

But here we don't need any installation process.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Creating arrays from Existing Data

In [1]:
import numpy as np
numbers = np.array([2, 3, 5, 7, 11])
numbers

array([ 2,  3,  5,  7, 11])

In [5]:
arr_0 = np.array([])
arr_0

array([], dtype=float64)

In [6]:
arr_0.ndim

1

In [ ]:
type(numbers)

numpy.ndarray

**Dimension**

1D array

In [ ]:
arr_0 = np.array(2)
arr_0


array(2)

In [ ]:
print(type(arr_0))

<class 'numpy.ndarray'>


In [ ]:
arr_1 = np.array([2])
arr_1


array([2])

In [ ]:
print(type(arr_1))

<class 'numpy.ndarray'>


In [ ]:
array_1D = np.array([2,4,5,6])
array_1D

array([2, 4, 5, 6])

2D array

In [ ]:
arr_2 = np.array([[1,2,3,4]])
arr_2

array([[1, 2, 3, 4]])

In [ ]:
arr_2.ndim

2

In [7]:
array_2D = np.array([[2,4,5,6],[2,4,5,6],[2,4,5,6]]) ## 3X4 array--(3 rows and 4 columns)
array_2D 

array([[2, 4, 5, 6],
       [2, 4, 5, 6],
       [2, 4, 5, 6]])

In [8]:
array_2D.shape

(3, 4)

3D array

In [9]:
array_3D = np.array([[[2,4,5,6],[2,4,5,6],[2,4,5,6]]])
array_3D 

array([[[2, 4, 5, 6],
        [2, 4, 5, 6],
        [2, 4, 5, 6]]])

In [10]:
array_3D .shape

(1, 3, 4)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## **Array Attributes**

In [ ]:
integers = np.array([[1, 2, 3], [4, 5, 6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [ ]:
strings = np.array(['apple','big','cat'])
strings 

array(['apple', 'big', 'cat'], dtype='<U5')

Checking an array's element types

In [ ]:
integers.dtype

dtype('int64')

In [ ]:
floats.dtype

dtype('float64')

Checking an array’s Dimensions and Shape

In [ ]:
array_1D.ndim

1

In [ ]:
array_2D.ndim

2

In [ ]:
array_3D.ndim

3

In [ ]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
integers.ndim

2

In [ ]:
integers.shape

(2, 3)

In [ ]:
integers.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array_2D.shape

(3, 4)

Checking an array’s Number of Elements and Element Size

In [ ]:
integers.size

6

In [ ]:
floats.size

5

#**Array Operators**

In [ ]:
x = np.arange(4)

In [ ]:
x

array([0, 1, 2, 3])

In [ ]:
x+10 #scalar addition is element wise

array([10, 11, 12, 13])

In [ ]:
x*2 #scalar multiplication is element wise

array([0, 2, 4, 6])

In [ ]:
x+x #array addition is element wise

array([0, 2, 4, 6])

In [ ]:
x*x #array multiplicatio is element wise

array([0, 1, 4, 9])

In [ ]:
x/10 #array division is element wise

array([0. , 0.1, 0.2, 0.3])

In [ ]:
x//10

array([0, 0, 0, 0])

In [ ]:
x**3

array([ 0,  1,  8, 27])

In [ ]:
x = np.array([[11,9,11],[2,15,18]])

In [ ]:
x>10

array([[ True, False,  True],
       [False,  True,  True]])

In [ ]:
x>=10

array([[ True, False,  True],
       [False,  True,  True]])

In [ ]:
x<10

array([[False,  True, False],
       [ True, False, False]])

In [ ]:
x<=10

array([[False,  True, False],
       [ True, False, False]])

In [ ]:
x==9

array([[False,  True, False],
       [False, False, False]])

In [ ]:
x!=11

array([[False,  True, False],
       [ True,  True,  True]])

#**NumPy Function**

In [ ]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [ ]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [ ]:
grades.max()

100

In [ ]:
grades.min()

70

In [ ]:
grades.sum()

1054

In [ ]:

grades.std()

8.792357792739987

In [ ]:
grades.mean()

87.83333333333333

In [ ]:
grades.var()

77.30555555555556

In [ ]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [ ]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

#**Indexing and Selection**

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[2]

array([35, 40, 45])

In [ ]:
arr_2d[0][2]

15

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])